apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: httpd-frontend

spec:
  selector:
    matchLabels:
      name: httpd-frontend

  template:
    metadata:
        labels:
          name: httpd-frontend
    spec:
      containers:
      - name: nginx
        image: httpd:2.4-alpine
  replicas: 3



