apiVersion: v1
kind: Pod
metadata:
  name: elephant
  labels:
    name: elephant
spec:
  containers:
    - name: polinux
      image: polinux/stress

      resources:
        requests:
          memory: "15Mi"
          cpu: 1
        limits:
           memory: "20Mi"
           cpu: 1







