


apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-log
  labels:
    name: pv-log
    app: pv-log
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /pv/log    
