apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-log-1
  labels:
    name: claim-log-1
    app: claim-log-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi



